// vuejs/src/modules/recipe/components/ingredients-list.vue
<template>
  <v-card v-if="recipeIngredients.length">
    <v-card-title
      primary-title
      class="justify-space-between">
      <h2>Your recipe ingredients list</h2>
      <v-flex md3>
        <v-text-field
          md3
          ng-model="recipeName"
          label="Recipe name"/>
      </v-flex>
    </v-card-title>
    <v-list>
      <v-list-group
        v-for="(ingredient, key) in recipeIngredients"
        :key="key"
        :value="ingredient.active">
        <v-list-tile slot="activator">
          <v-list-tile-content>
            <v-list-tile-title>{{ ingredient.name }} {{ ingredient.nutrients.calories }}cal for {{ ingredient.nutrients.totalWeight }}gr </v-list-tile-title>
          </v-list-tile-content>
          <v-list-tile-action
            :id="`remove-ingredient-${key}`"
            @click="removeIngredient(key)">
            <v-icon>delete</v-icon>
          </v-list-tile-action>
        </v-list-tile>
        <nutrients-insight :nutrients="ingredient.nutrients"/>
      </v-list-group>
    </v-list>
    <v-card-actions class="justify-end">
      <v-btn @click="removeAllIngredients">Remove all ingredients</v-btn>
      <v-btn
        color="primary"
        @click="saveRecipe(recipeName)">Save recipe</v-btn>
    </v-card-actions>
  </v-card>
</template>

<script>
import NutrientsInsight from '@/modules/recipe/components/nutrients-insight.vue';

import { mapGetters, mapActions } from 'vuex';
import * as recipeTypes from '@/modules/recipe/store/types';

export default {
  data () {
    return {
      recipeName: '',
    };
  },

  components: {
    NutrientsInsight,
  },

  computed: {
    ...mapGetters('recipe', {
      recipeIngredients: recipeTypes.GET_RECIPE,
    }),
  },

  methods: {
    ...mapActions('recipe', {
      removeIngredient: recipeTypes.REMOVE_INGREDIENT,
      removeAllIngredients: recipeTypes.REMOVE_ALL_INGREDIENTS,
      saveRecipe: recipeTypes.SAVE_RECIPE,
    }),
  },
};
</script>

// angular/src/app/ingredients-list/ingredients-list.component.ts
import { IIngredient } from './../core/recipe.interface';
import { Component, OnInit } from '@angular/core';
import RecipeService from '../core/recipe.service';

@Component({
  selector: 'app-ingredients-list',
  templateUrl: './ingredients-list.component.html',
  styleUrls: ['./ingredients-list.component.scss']
})
export class IngredientsListComponent implements OnInit {
  public recipeIngredients: IIngredient[] = [];
  public recipeName = '';

  constructor(private recipeService: RecipeService) { }

  ngOnInit() {
    this.recipeService.recipeIngredients$.subscribe((recipeIngredientsData) => {
      this.recipeIngredients = recipeIngredientsData;
    });
  }

  removeIngredient(index: number) {
    this.recipeService.removeIngredient(index);
  }

  removeAllIngredients() {
    this.recipeService.removeAllIngredients();
  }

  saveRecipe () {
    this.recipeService.saveRecipe(this.recipeName);
  }
}

<mat-card *ngIf="recipeIngredients.length">
  <mat-card-header
    fxLayout.xs="column"
    fxLayoutAlign="space-between">
    <mat-card-title>
      <h2>Your recipe ingredients list</h2>
    </mat-card-title>
    <mat-form-field>
      <input
        matInput
        placeholder="Recipe name"
        name="recipeName"
        [(ngModel)]="recipeName">
    </mat-form-field>
  </mat-card-header>
  <mat-card-content>
    <mat-accordion>
      <mat-expansion-panel *ngFor="let ingredient of recipeIngredients; let i = index">
        <mat-expansion-panel-header>
            <p matLine>{{ ingredient.name }} {{ ingredient.nutrients.calories }}cal for {{ ingredient.nutrients.totalWeight }}gr </p>
            <button mat-button (click)="removeIngredient(i)">
              <mat-icon matListIcon>delete</mat-icon>
            </button>
          </mat-expansion-panel-header>
        <app-nutrients-insight [nutrients]="ingredient.nutrients"></app-nutrients-insight>
      </mat-expansion-panel>
    </mat-accordion>
  </mat-card-content>
  <mat-card-actions
    fxLayout="row"
    fxLayoutAlign="end">
      <button
        mat-button
        (click)="removeAllIngredients()">
        Remove all ingredients
      </button>
      <button
        mat-raised-button
        color="primary"
        (click)="saveRecipe()">
        Save recipe
      </button>
  </mat-card-actions>
</mat-card>
