// react/src/modules/recipe/components/ingredient-nutrients/IngredientNutrients.jsx
import React, { Component } from "react";
import recipeService from "../../recipe.service";
import { Chip, Typography, Grid } from "@material-ui/core";

class IngredientNutrients extends Component {
  get allLabels () {
    const dietsLabels = recipeService.getDietLabels(this.props.nutrients.dietLabels);
    const healthLabels = recipeService.getHealthLabels(this.props.nutrients.healthLabels);
    
    return dietsLabels.concat(healthLabels);
  }
  
  get macroNutrientsData () {
    return recipeService.getMacroNutrientsList(this.props.nutrients.totalNutrients);
  }

  render() {
    if (!this.props.nutrients) return false;
    
    const nutrientsView = this.macroNutrientsData.map((nutrient, index) => {
      const quantity = Math.round(nutrient.quantity);

      return (
        <div key={index}>
          <Typography
            gutterBottom
            component="h3">
            { nutrient.label }
          </Typography>
          <Typography
            gutterBottom
            paragraph
            component="p">
              { quantity } { nutrient.unit }
            </Typography>
        </div>
      );
    });
    const allLabelsView = this.allLabels.map((label, index) => 
      <Chip key={index} label={label}/>
    );

    return (
      <Grid 
        container
        spacing={8}
        alignItems="center"
        justify="center">
        <Grid
          container 
          justify="space-between">
          {nutrientsView}
        </Grid>
        <Grid
          container
          alignItems="center"
          justify="center">
          {allLabelsView}
        </Grid>
      </Grid>
    );
  }
}
export default IngredientNutrients;

// vuejs/src/modules/recipe/components/ingredient-nutrients.vue
<template>
  <div>
    <v-layout
      justify-space-between
      align-center
      row>
      <v-flex
        :key="key"
        v-for="(nutrient, key) in macroNutrientsData"
        text-xs-center>
        <h3 class="pa-2">{{ nutrient.label }}</h3>
        <p>{{ nutrient.quantity | round(2) }}{{ nutrient.unit }}</p>
      </v-flex>
    </v-layout>

    <div class="text-xs-center pa-2">
      <v-chip
        :key="key"
        v-for="(label, key) in allLabels"
        v-if="label">
        {{ label }}
      </v-chip>
    </div>
  </div>
</template>

<script>
import recipeService from '@/core/recipe.service';

export default {
  props: {
    nutrients: {
      type: Object,
      required: true,
    },
  },

  computed: {
    allLabels () {
      const dietsLabels = recipeService.getDietLabels(this.nutrients.dietLabels);
      const healthLabels = recipeService.getHealthLabels(this.nutrients.healthLabels);

      return dietsLabels.concat(healthLabels);
    },

    macroNutrientsData () {
      return recipeService.getMacroNutrientsList(this.nutrients.totalNutrients);
    },
  },
};
</script>
