// react/src/recipe/components/ingredient-nutrients/IngredientNutrients.js
import React, { Component } from "react";
import recipeService from "../../../core/recipe.service";

class IngredientNutrients extends Component {

  get allLabels () {
    const dietsLabels = recipeService.getDietLabels(this.props.nutrients.dietLabels);
    const healthLabels = recipeService.getHealthLabels(this.props.nutrients.healthLabels);
    
    return dietsLabels.concat(healthLabels);
  }
  
  get macroNutrientsData () {
    return recipeService.getMacroNutrientsList(this.props.nutrients.totalNutrients);
  }

  render() {
    const nutrientsView = this.macroNutrientsData.map((nutrient) => 
      <div>
          <h3 class="pa-2">{ nutrient.label }</h3>
          <p>{ nutrient.quantity } { nutrient.unit }</p>
      </div>
    )
    const allLabelsView = this.allLabels.map((label) => <li>{label}</li>);

    return (
      <div>
        <div className="u-text-center">
          {nutrientsView}
        </div>
        <ul>
          {allLabelsView}
        </ul>
      </div>
    );
  }
}
export default IngredientNutrients;

// vuejs/src/modules/recipe/components/ingredient-nutrients.vue
<template>
  <div>
    <v-layout
      justify-space-between
      align-center
      row>
      <v-flex
        :key="key"
        v-for="(nutrient, key) in macroNutrientsData"
        text-xs-center>
        <h3 class="pa-2">{{ nutrient.label }}</h3>
        <p>{{ nutrient.quantity | round(2) }}{{ nutrient.unit }}</p>
      </v-flex>
    </v-layout>

    <div class="text-xs-center pa-2">
      <v-chip
        :key="key"
        v-for="(label, key) in allLabels"
        v-if="label">
        {{ label }}
      </v-chip>
    </div>
  </div>
</template>

<script>
import recipeService from '@/core/recipe.service';

export default {
  props: {
    nutrients: {
      type: Object,
      required: true,
    },
  },

  computed: {
    allLabels () {
      const dietsLabels = recipeService.getDietLabels(this.nutrients.dietLabels);
      const healthLabels = recipeService.getHealthLabels(this.nutrients.healthLabels);

      return dietsLabels.concat(healthLabels);
    },

    macroNutrientsData () {
      return recipeService.getMacroNutrientsList(this.nutrients.totalNutrients);
    },
  },
};
</script>
