// angular/src/app/recipe/recipes-list/recipes-list.component.ts
import { Component, OnInit, ChangeDetectionStrategy } from '@angular/core';
import { IRecipe } from '@/recipe/recipe.interface';
import RecipeStore from '@/recipe/store/recipeStore';

@Component({
  selector: 'app-recipes',
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './recipes-list.component.html',
  styleUrls: ['./recipes-list.component.scss']
})
export class RecipesListComponent implements OnInit {
  public recipes$ = this.recipeStore.get<IRecipe[]>('recipes');

  constructor(
    private recipeStore: RecipeStore,
  ) { }

  ngOnInit() {
  }
}

<h2>List of recipes you created</h2>
<div
  *ngIf="(recipes$ | async)?.length; else loading"
  fxLayout="row"
  fxLayoutGap="20px">
  <div
    fxFlex
    fxFlex.gt-sm="25"
    *ngFor="let recipe of recipes$ | async">
    <mat-card>
      <mat-card-header>
        <mat-card-title>
          <h2>{{ recipe.name }}</h2>
        </mat-card-title>
      </mat-card-header>
      <mat-card-content>
      <mat-list *ngFor="let ingredient of recipe.ingredients">
        <mat-list-item>{{ ingredient.name }} {{ ingredient.nutrients.calories }}cal for {{ ingredient.nutrients.totalWeight }}gr</mat-list-item>
      </mat-list>
      </mat-card-content>
    </mat-card>
  </div>
</div>
<ng-template #loading>
  <div fxLayout="column">
    <div fxFlex="50">
      <p>You don't have any recipes yet</p>
      <a
        mat-button
        color="primary"
        routerLink="/">Create recipe</a>
    </div>
  </div>
</ng-template>

// vuejs/src/modules/recipe/components/recipes-list.vue
<template>
  <v-container grid-list-md>
    <v-layout
      row
      wrap>
      <v-flex
        md4
        v-for="(recipe, key) in recipes"
        :key="key">
        <v-card height="100%">
          <v-card-title primary-title>
            <h2>{{ recipe.name }}</h2>
          </v-card-title>
          <v-list>
            <v-list-tile
              v-for="(ingredient, key) in recipe.ingredients"
              :key="key">
              <v-list-tile-content>
                <v-list-tile-title>{{ ingredient.name }} {{ ingredient.nutrients.calories }}cal for {{ ingredient.nutrients.totalWeight }}gr </v-list-tile-title>
              </v-list-tile-content>
            </v-list-tile>
          </v-list>
        </v-card>
      </v-flex>
    </v-layout>
    <v-layout
      v-if="!recipes.length"
      column
      justify-center
      align-center="">
      <v-flex md6>
        <p class="ma-2">You don't have any recipes yet</p>
        <v-btn
          color="primary"
          to="/">Create recipe</v-btn>
      </v-flex>
    </v-layout>
  </v-container>
</template>

<script>
import { mapGetters } from 'vuex';
import * as recipeTypes from '@/modules/recipe/store/types';

export default {
  computed: {
    ...mapGetters('recipe', {
      recipes: recipeTypes.GET_RECIPES,
    }),
  },
};
</script>
