// react/src/recipe/recipe-creator/RecipeCreator.js
import './RecipeCreator.css';

import React, { Component } from 'react';
import { connect } from 'react-redux';
import { Grid } from '@material-ui/core';

import SearchIngredient from '../components/search-ingredient/SearchIngredient';
import IngredientsList from '../components/ingredients-list/IngredientsList';
import IngredientsData from '../components/ingredients-data/IngredientsData';
import * as ingredientsActions from '../actions/ingredientsActions';
import * as recipesActions from '../actions/recipesActions';
import recipeService from '../../core/recipe.service';
import NutritionMacro from '../components/nutrition-macro/NutritionMacro';
import nutritionService from '../../core/nutrition.service';

class RecipeCreator extends Component {

	get totalCalories () {
    return nutritionService.getTotalCalories(this.props.ingredients);
  }

  get totalWeight () {
    return nutritionService.getTotalWeight(this.props.ingredients);
  }

	addIngredient = (ingredientName, numberOfServings) => {
		this.props.dispatch(ingredientsActions.fetchIngredientPending());

		recipeService.fetchIngredient(ingredientName, numberOfServings)
			.then((data) => {
				this.props.dispatch(ingredientsActions.addIngredient(data));
				this.updateIngredientsTotalNutrition();
			})
			.catch((error) => {
				this.props.dispatch(ingredientsActions.fetchIngredientRejected(error));
			});
  }

  removeIngredient = (index) => {
		this.props.dispatch(ingredientsActions.removeIngredient(index));
		if (!this.props.ingredients.length) {
			this.props.dispatch(ingredientsActions.removeAllIngredientsTotalNutritients());
		}
  }

  removeAllIngredients = () => {
		this.props.dispatch(ingredientsActions.removeAllIngredients());
		this.props.dispatch(ingredientsActions.removeAllIngredientsTotalNutritients());
	}
	
	saveRecipe = (name) => {
		const recipe = {
			ingredients: [ ...this.props.ingredients ],
			name,
		};
		this.removeAllIngredients();
		this.props.dispatch(recipesActions.saveRecipe(recipe));
	}

	updateIngredientsTotalNutrition = () => {
		const totalNutrients = nutritionService.getTotalNutrients(this.props.ingredients, this.totalCalories);
		this.props.dispatch(ingredientsActions.updateIngredientsTotalNutritients(totalNutrients));
	}

	render() {
		return (
			<Grid container spacing={16}>
				<Grid item xs={12}>
					<SearchIngredient
						add={this.addIngredient}
						isFetching={this.props.isFetching}/>
				</Grid>
				<Grid item xs={12}>
					<IngredientsList 
						ingredients={this.props.ingredients}
						remove={this.removeIngredient}
						removeAll={this.removeAllIngredients}
						save={this.saveRecipe}/>
				</Grid>
				<Grid item xs={12}>
					<IngredientsData 
						totalNutrients={this.props.totalNutrients}
						totalWeight={this.totalWeight}
						totalCalories={this.totalCalories}/>
				</Grid>
				<Grid item xs={12}>
					<NutritionMacro totalNutrients={this.props.totalNutrients}/>
				</Grid>
			</Grid>
		);
	}
}

const mapStateToProps = (state) => ({
	ingredients: state.ingredients.ingredients,
	totalNutrients: state.ingredients.totalNutrients,
	isFetching: state.ingredients.isFetching,
});

export default connect(mapStateToProps)(RecipeCreator);

// angular/src/app/modules/recipe/recipe-creator/recipe-creator.component.ts
import NutritionService from '@/modules/recipe/nutrition.service';
import ToastService from '@/core/toast.service';
import { Component, OnInit } from '@angular/core';
import { IIngredient, IRecipe } from '@/modules/recipe/recipe.interface';
import RecipeService from '@/modules/recipe/recipe.service';
import RecipeStore from '@/modules/recipe/store/recipe-store';

@Component({
  selector: 'app-recipe-creator',
  templateUrl: './recipe-creator.component.html',
  styleUrls: ['./recipe-creator.component.scss']
})
export class RecipeCreatorComponent implements OnInit {
  public ingredients$ = this.recipeStore.get<IIngredient[]>('ingredients');
  public totalNutrients$ = this.recipeStore.get<any[]>('totalNutrients');
  public totalWeight$ = this.recipeStore.get<number>('totalWeight');
  public totalCalories$ = this.recipeStore.get<number>('totalCalories');

  constructor(
    private recipeStore: RecipeStore,
    private toastService: ToastService,
    private nutritionService: NutritionService,
  ) { }

  ngOnInit() {
  }


  public addIngredient(event) {
    this.recipeStore
      .addIngredient(event)
      .subscribe(
        () => {},
        (error) => this.toastService.show('ERROR', error.message),
      );
  }

  public removeIngredient(event) {
    this.recipeStore
      .removeIngredient(event);
  }

  public removeAllIngredients() {
    this.recipeStore.removeAllIngredients();
  }

  public saveRecipe (event) {
    this.recipeStore.saveRecipe(event);
  }
}

<div
  fxLayout="column"
  fxLayoutGap="10px">
  <app-search-ingredient
    fxFlex
    (add)="addIngredient($event)">
  </app-search-ingredient>
  <app-ingredients-list
    fxFlex
    [ingredients]="ingredients$ | async"
    (remove)="removeIngredient($event)"
    (removeAll)="removeAllIngredients($event)"
    (save)="saveRecipe($event)">
  </app-ingredients-list>
  <app-ingredients-data
    fxFlex
    [totalNutrients]="totalNutrients$ | async"
    [totalWeight]="totalWeight$ | async"
    [totalCalories]="totalCalories$ | async">
  </app-ingredients-data>
  <app-nutrition-macro
    fxFlex
    [totalNutrients]="totalNutrients$ | async">
  </app-nutrition-macro>
</div>
