// vuejs/src/modules/recipe/components/ingredients-list.vue
<template>
  <v-card v-if="ingredients.length">
    <v-card-title
      primary-title
      class="justify-space-between"
    >
      <h2 class="headline">
        Your recipe ingredients list
      </h2>
      <v-flex md3>
        <v-text-field
          md3
          v-model="recipeName"
          label="Recipe name"
        />
      </v-flex>
    </v-card-title>
    <v-list>
      <ingredient-details
        v-for="(ingredient, key) in ingredients"
        :key="key"
        :index="key"
        :ingredient="ingredient"
        :remove="remove"
      />
    </v-list>
    <v-card-actions class="justify-end">
      <v-btn
        flat
        id="remove-all-button"
        @click="removeAll"
      >
        Remove all ingredients
      </v-btn>
      <v-btn
        id="save-button"
        color="primary"
        @click="saveRecipe()"
      >
        Save recipe
      </v-btn>
    </v-card-actions>
  </v-card>
</template>

<script>
import IngredientDetails from '@/modules/recipe/components/ingredient-details';

export default {
  components: {
    IngredientDetails,
  },

  data () {
    return {
      recipeName: '',
    };
  },

  props: {
    ingredients: {
      type: Array,
      required: true,
    },
    remove: {
      type: Function,
      required: true,
    },
    removeAll: {
      type: Function,
      required: true,
    },
    save: {
      type: Function,
      required: true,
    },
  },

  methods: {
    saveRecipe () {
      this.save(this.recipeName);
      this.recipeName = '';
    },
  },
};
</script>

<style type="scss">
.list__tile__title {
  max-width: 48vw;
}
</style>

// react/src/recipe/components/ingredients-list/IngredientsList.js
import React, { Component } from 'react';
import { 
  TextField, Button, Typography, Grid,
} from '@material-ui/core';
import IngredientDetails from '../ingredient-details/IngredientDetails';
import './IngredientsList.css';

class IngredientsList extends Component {
  constructor(props) {
    super(props);

    this.state = {
      recipeName: '',
    };
  }

  onRecipeNameChange = (event) => {
    this.setState({ recipeName : event.target.value });
  }

  save = () => {
    this.props.save(this.state.recipeName);
  }

  render() {
    if (!this.props.ingredients.length) return '';
  
    const ingredientsList = this.props.ingredients.map((ingredient, index) => 
      <IngredientDetails key={index} index={index} ingredient={ingredient} remove={this.props.remove}/>
    )
    
    return(
      <Grid 
        container
        direction="column">
        <Grid
          container
          direction="row"
          justify="space-between"
          alignItems="center">
          <Typography
            gutterBottom 
            variant="headline"
            component="h2">
            Your recipe ingredients list
          </Typography>          
          <form>
            <TextField
              label="Recipe name"
              value={this.state.recipeName} 
              onChange={this.onRecipeNameChange}
            />
          </form>
        </Grid>
        <Grid
          item
          className="ingredients-list__list">
          {ingredientsList}
        </Grid>
        <Grid
          container
          spacing={8}
          justify="flex-end">
          <Grid item>
            <Button
              onClick={this.props.removeAll}>
              Remove all ingredients
            </Button>
          </Grid>
          <Grid item>
            <Button
              variant="raised"
              color="primary"
              onClick={this.save}>
              Save recipe
            </Button>
          </Grid>
        </Grid>
      </Grid>
    );
  }
}

export default IngredientsList;
