// angular/src/app/recipe/recipe-creator/recipe-creator.component.ts
import { Component, OnInit } from '@angular/core';
import { IIngredient, IRecipe } from '@/recipe/recipe.interface';
import RecipeService from '@/recipe/recipe.service';

@Component({
  selector: 'app-recipe-creator',
  templateUrl: './recipe-creator.component.html',
  styleUrls: ['./recipe-creator.component.scss']
})
export class RecipeCreatorComponent implements OnInit {
  public ingredients$ = this.recipeService.get<IIngredient[]>('ingredients');

  constructor(
    private recipeService: RecipeService,
  ) { }

  ngOnInit() {
  }

  public addIngredient(event: any) {
    this.recipeService
      .addIngredient(event)
      .subscribe();
  }

  public removeIngredient(event: any) {
    this.recipeService
      .removeIngredient(event);
  }

  public removeAllIngredients() {
    this.recipeService.removeAllIngredients();
  }

  public saveRecipe (event) {
    this.recipeService.saveRecipe(event);
  }

}

<div
  fxLayout="column"
  fxLayoutGap="10px">
  <app-search-ingredient
    fxFlex
    (add)="addIngredient($event)">
  </app-search-ingredient>
  <app-ingredients-list
    fxFlex
    [ingredients]="ingredients$ | async"
    (remove)="removeIngredient($event)"
    (removeAll)="removeAllIngredients($event)"
    (save)="saveRecipe($event)">
  </app-ingredients-list>
  <app-recipe-data
    fxFlex
    [ingredients]="ingredients$ | async">
  </app-recipe-data>
</div>

// react/src/recipe/recipe-creator/RecipeCreator.js
import './RecipeCreator.css';

import React, { Component } from 'react';
import { connect } from 'react-redux';

import SearchIngredient from '../components/search-ingredient/SearchIngredient';
import IngredientsList from '../components/ingredients-list/IngredientsList';
import IngredientsData from '../components/ingredients-data/IngredientsData';
import * as ingredientsActions from '../actions/ingredientsActions';
import * as recipesActions from '../actions/recipesActions';
import recipeService from '../../core/recipe.service';

class RecipeCreator extends Component {
	addIngredient = (ingredientName, numberOfServings) => {
		this.props.dispatch(ingredientsActions.fetchIngredientPending());

		recipeService.fetchIngredient(ingredientName, numberOfServings)
			.then((data) => {
				this.props.dispatch(ingredientsActions.addIngredient(data));
			})
			.catch((error) => {
				this.props.dispatch(ingredientsActions.fetchIngredientRejected(error));
			});
  }

  removeIngredient = (index) => {
    this.props.dispatch(ingredientsActions.removeIngredient(index));
  }

  removeAllIngredients = () => {
		this.props.dispatch(ingredientsActions.removeAllIngredients());
	}
	
	saveRecipe = (name) => {
		const recipe = {
			ingredients: [ ...this.props.ingredients ],
			name,
		};
		this.removeAllIngredients();
		this.props.dispatch(recipesActions.saveRecipe(recipe));
	}

	render() {
		return (
			<div>
				<SearchIngredient add={this.addIngredient}/>
				<IngredientsList 
          ingredients={this.props.ingredients}
          remove={this.removeIngredient}
          removeAll={this.removeAllIngredients}
					save={this.saveRecipe}/>
        <IngredientsData ingredients={this.props.ingredients}/>
			</div>
		);
	}
}

const mapStateToProps = (state) => ({
	ingredients: state.ingredients.ingredients,
});

export default connect(mapStateToProps)(RecipeCreator);
