// vuejs/src/modules/recipe/components/nutrients-chart.vue
<template>
  <div class="text-xs-center"/>
</template>

<script>
import * as d3 from 'd3';

export default {

  props: {
    nutritionData: {
      type: Array,
      required: true,
    },
  },

  methods: {
    drawChart () {
      const dataset = {
        children: this.nutritionData,
      };
      const diameter = 320;
      const color = d3.scaleOrdinal().range(['#C5E1A5', '#AED581', '#9CCC65']);

      const bubble = d3.pack(dataset)
        .size([diameter, diameter])
        .padding(1.5);

      const svg = d3.select(this.$el)
        .append('svg')
        .attr('width', diameter)
        .attr('height', diameter)
        .attr('class', 'bubble');

      const nodes = d3.hierarchy(dataset)
        .sum((d) => d.totalQuantity && d.totalQuantity.percentage);

      const node = svg.selectAll('.node')
        .data(bubble(nodes).descendants())
        .enter()
        .filter((d) => !d.children)
        .append('g')
        .attr('class', 'node')
        .attr('transform', (d) => `translate(${d.x}, ${d.y})`);

      node
        .append('title')
        .text((d) => d.totalQuantity && `${d.totalQuantity.label} : ${d.totalQuantity.percentage}%`);

      node
        .append('circle')
        .attr('r', (d) => d.r)
        .style('fill', (d, i) => color(i));

      node.append('text')
        .attr('dy', '.2em')
        .style('text-anchor', 'middle')
        .text((d) => d.data.totalQuantity.label.substring(0, d.r / 3))
        .attr('font-family', 'sans-serif')
        .attr('font-size', (d) => d.r / 5)
        .attr('fill', 'black');

      node.append('text')
        .attr('dy', '1.3em')
        .style('text-anchor', 'middle')
        .text((d) => `${d.data.totalQuantity.percentage}%`)
        .attr('font-size', (d) => d.r / 7)
        .attr('fill', 'black');

      d3.select(this.$el)
        .style('height', `${diameter}px`);
    },
  },

  watch: {
    nutritionData () {
      d3.select(this.$el)
        .selectAll('svg')
        .remove();

      this.drawChart();
    },
  },

  mounted () {
    this.drawChart();
  },
};
</script>

// angular/src/app/recipe/components/nutrients-chart/nutrients-chart.component.ts
import * as d3 from 'd3';
import { Component, OnInit, Input, ElementRef, OnChanges } from '@angular/core';
import { INutrient } from '@/recipe/recipe.interface';

@Component({
  selector: 'app-nutrients-chart',
  templateUrl: './nutrients-chart.component.html',
  styleUrls: ['./nutrients-chart.component.scss']
})
export class NutrientsChartComponent implements OnInit, OnChanges {
  @Input()
  public nutritionData: INutrient[];

  constructor(private elementRef: ElementRef) { }

  ngOnInit() {
    this.drawChart();
  }

  ngOnChanges() {
    this.clearChart();
    this.drawChart();
  }

  drawChart () {
    const dataset = {
      children: this.nutritionData,
    };
    const diameter = 320;
    const color = d3.scaleOrdinal().range(['#C5E1A5', '#AED581', '#9CCC65']);

    const bubble = d3.pack()
      .size([diameter, diameter])
      .padding(1.5);

    const svg = d3.select(this.elementRef.nativeElement)
      .select('div')
      .append('svg')
      .attr('width', diameter)
      .attr('height', diameter)
      .attr('class', 'bubble');

    const nodes = d3.hierarchy(dataset)
      .sum((d: any) => d.totalQuantity && d.totalQuantity.percentage);

    const node = svg.selectAll('.node')
      .data(bubble(nodes).descendants())
      .enter()
      .filter((d: any) => !d.children)
      .append('g')
      .attr('class', 'node')
      .attr('transform', (d: any) => `translate(${d.x}, ${d.y})`);

    node
      .append('title')
      .text((d: any) => d.totalQuantity && `${d.totalQuantity.label} : ${d.totalQuantity.percentage}%`);

    node
      .append('circle')
      .attr('r', (d: any) => d.r)
      .style('fill', (d, i) =>  color(i + '') as string);

    node.append('text')
      .attr('dy', '.2em')
      .style('text-anchor', 'middle')
      .text((d: any) => d.data.totalQuantity.label.substring(0, d.r / 3))
      .attr('font-family', 'sans-serif')
      .attr('font-size', (d: any) => d.r / 5)
      .attr('fill', 'black');

    node.append('text')
      .attr('dy', '1.3em')
      .style('text-anchor', 'middle')
      .text((d: any) => `${d.data.totalQuantity.percentage}%`)
      .attr('font-size', (d: any) => d.r / 7)
      .attr('fill', 'black');

    d3.select(this.elementRef.nativeElement)
      .style('height', `${diameter}px`);
  }

  clearChart () {
    d3.select(this.elementRef.nativeElement)
      .selectAll('svg')
      .remove();
  }
}
