// vuejs/src/components/recipe-details.vue
<template functional>
  <v-card height="100%">
    <v-card-title primary-title>
      <h2 class="headline">
        {{ props.recipe.name }}
      </h2>
    </v-card-title>
    <v-list>
      <v-list-tile
        v-for="(ingredient, key) in props.recipe.ingredients"
        :key="key"
      >
        <v-list-tile-content>
          <v-list-tile-title>{{ ingredient.name }} {{ ingredient.nutrients.calories }}cal for {{ ingredient.nutrients.totalWeight }}gr </v-list-tile-title>
        </v-list-tile-content>
      </v-list-tile>
    </v-list>
  </v-card>
</template>

// angular/src/app/modules/recipe/components/recipe-details/recipe-details.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-recipe-details',
  templateUrl: './recipe-details.component.html',
  styleUrls: ['./recipe-details.component.scss']
})
export class RecipeDetailsComponent implements OnInit {
  @Input()
  public recipe = {};

  constructor() { }

  ngOnInit() {
  }

}

<mat-card>
  <mat-card-header>
    <mat-card-title>
      <h2 class="mat-headline">{{ recipe.name }}</h2>
    </mat-card-title>
  </mat-card-header>
  <mat-card-content>
  <mat-list *ngFor="let ingredient of recipe.ingredients">
    <mat-list-item>{{ ingredient.name }} {{ ingredient.nutrients.calories }}cal for {{ ingredient.nutrients.totalWeight }}gr</mat-list-item>
  </mat-list>
  </mat-card-content>
</mat-card>
