// vuejs/src/modules/recipe/components/search-ingredient.vue
<template>
  <v-card class="search-ingredient">
    <v-card-title primary-title>
      <h2>What do you have in your fridge?</h2>
    </v-card-title>
    <form
      novalidate
      id="search-ingredient-form"
      @submit.prevent="addIngredient">
      <v-layout
        v-bind="rowMdLayout"
        justify-space-between
        align-center
        px-4>
        <v-text-field
          class="ma-1"
          label="Ingredient and quantity"
          placeholder="Example: 200gr chicken"
          v-model="ingredient"/>
        <v-text-field
          class="ma-1"
          label="Number of servings"
          v-model.number="numberOfServing"/>
        <v-btn
          type="submit"
          :disabled="!ingredient"
          color="primary"
          :loading="isLoading">
          Add
        </v-btn>
      </v-layout>
    </form>
  </v-card>
</template>

<script>
import layoutMixin from '@/core/layout.mixin';

import { mapActions } from 'vuex';
import * as recipeTypes from '@/modules/recipe/store/types';

export default {
  data: () => {
    return {
      ingredient: '',
      numberOfServing: 1,
      isLoading: false,
    };
  },

  mixins: [layoutMixin],

  methods: {
    ...mapActions('recipe', {
      addToRecipe: recipeTypes.ADD_INGREDIENT,
    }),

    addIngredient () {
      this.isLoading = true;
      this.addToRecipe({
        ingredient: this.ingredient,
        numberOfServing: this.numberOfServing,
      })
        .then(() => {
          this.isLoading = false;
          this.ingredient = '';
          this.numberOfServing = 1;
        })
        .catch(() => this.isLoading = false);
    },
  },
};
</script>

<style lang="scss">
.search-ingredient {
  margin-top: -100px;
}
</style>

// angular/src/app/recipe/components/search-ingredient/search-ingredient.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';

@Component({
  selector: 'app-search-ingredient',
  templateUrl: './search-ingredient.component.html',
  styleUrls: ['./search-ingredient.component.scss']
})
export class SearchIngredientComponent implements OnInit {
  public ingredient: string;
  public numberOfServing = 1;

  @Output()
  add = new EventEmitter<FormGroup>();


  form = this.fb.group({
    numberOfServing: '1',
    ingredient: '',
  });

  constructor(private fb: FormBuilder) {}


  get isDisabled(): boolean {
    return !this.form.value.ingredient;
  }

  ngOnInit() {
  }

  onSubmit() {
    this.add.emit(this.form.value);
    this.form.setValue({
      numberOfServing: '1',
      ingredient: '',
    });
  }
}

<mat-card class="search-ingredient">
  <mat-card-header>
    <mat-card-title>
      <h2>What do you have in your fridge?</h2>
    </mat-card-title>
  </mat-card-header>
  <mat-card-content>
    <form
      [formGroup]="form"
      (submit)="onSubmit()">
      <div
        fxLayout.xs="column"
        fxLayoutAlign="space-between center">
        <mat-form-field fxFlex="50%">
          <input
            matInput
            placeholder="Ingredient and quantity"
            formControlName="ingredient">
          <mat-hint align="start">
            <strong>Example: 200gr chicken</strong>
          </mat-hint>
        </mat-form-field>
        <mat-form-field>
          <input
            matInput
            fxFlex="20%"
            placeholder="Number of servings"
            formControlName="numberOfServing">
        </mat-form-field>
        <button
          mat-button
          disabled="{{ isDisabled }}"
          mat-raised-button
          type="submit"
          color="primary">
          Add
        </button>
      </div>
    </form>

  </mat-card-content>
</mat-card>
