// vuejs/src/components/ingredients-data.vue
<template functional>
  <v-flex
    xs12
    v-if="props.totalNutrients.length"
  >
    <v-card>
      <v-card-title primary-title>
        <h2 class="headline">
          Total nutrients
        </h2>
      </v-card-title>
      <v-card-text>
        <h3 class="subheading">
          Calories: {{ props.totalCalories }}cal
        </h3>
        <h3 class="subheading">
          Total Weight: {{ props.totalWeight }}gr
        </h3>
        <v-layout
          align-end
          justify-space-between
        >
          <v-flex text-xs-center>
            <p class="body-1">
              Total Nutrients
            </p>
            <p class="body-1">
              Total Daily percentage
            </p>
          </v-flex>

          <v-flex
            :key="key"
            v-for="(nutrient, key) in props.totalNutrients"
            text-xs-center
          >
            <h3 class="subheading pa-2">
              {{ nutrient.label }}
            </h3>
            <p class="body-1">
              {{ nutrient.totalQuantity.quantity | round(2) }}{{ nutrient.totalQuantity.unit }}
            </p>
            <p class="body-1">
              {{ nutrient.totalDaily.quantity | round(2) }}{{ nutrient.totalDaily.unit }}
            </p>
          </v-flex>
        </v-layout>
      </v-card-text>
    </v-card>
  </v-flex>
</template>

// react/src/modules/recipe/components/ingredients-data/IngredientsData.jsx
import React, { Component } from 'react';
import './IngredientsData.css';

import { Card, CardContent, Typography, Grid } from '@material-ui/core';
import NutrientDetails from '../nutritient-details/NutrientDetails';

class IngredientsData extends Component {
  render() {
    if (!this.props.totalNutrients || !this.props.totalNutrients.length) return false;

    const nutrientsDetails = this.props.totalNutrients.map((nutrient, index) => 
        <div className="u-text-center" key={index}>
          <NutrientDetails key={index} nutrient={nutrient}/>
        </div>
      );

    return(
      <Card>
        <CardContent>
          <Typography
            gutterBottom 
            variant="headline"
            component="h2">
            Total nutrients
          </Typography>          
          <Typography
            gutterBottom 
            component="h3">
            Calories: { this.props.totalCalories }cal
          </Typography>
          <Typography
            gutterBottom 
            component="h3">
            Total Weight: { this.props.totalWeight }gr
          </Typography>
          <Grid
            container 
            alignItems="flex-end"
            justify="space-between">
            <header>
              <Typography
                gutterBottom
                paragraph
                component="p">
                Total Nutrients
              </Typography>
              <Typography
                gutterBottom
                paragraph
                component="p">
                  Total Daily percentage
              </Typography>
            </header>
            {nutrientsDetails}
          </Grid>
        </CardContent>
      </Card>
    );
  }
}

export default IngredientsData;
