// vuejs/src/components/ingredients-data.vue
<template functional>
  <v-flex
    xs12
    v-if="props.totalNutrients.length"
  >
    <v-card>
      <v-card-title primary-title>
        <h2 class="headline">
          Total nutrients
        </h2>
      </v-card-title>
      <v-card-text>
        <h3 class="subheading">
          Calories: {{ props.totalCalories }}cal
        </h3>
        <h3 class="subheading">
          Total Weight: {{ props.totalWeight }}gr
        </h3>
        <v-layout
          align-end
          justify-space-between
        >
          <v-flex text-xs-center>
            <p class="body-1">
              Total Nutrients
            </p>
            <p class="body-1">
              Total Daily percentage
            </p>
          </v-flex>

          <v-flex
            :key="key"
            v-for="(nutrient, key) in props.totalNutrients"
            text-xs-center
          >
            <h3 class="subheading pa-2">
              {{ nutrient.label }}
            </h3>
            <p class="body-1">
              {{ nutrient.totalQuantity.quantity | round(2) }}{{ nutrient.totalQuantity.unit }}
            </p>
            <p class="body-1">
              {{ nutrient.totalDaily.quantity | round(2) }}{{ nutrient.totalDaily.unit }}
            </p>
          </v-flex>
        </v-layout>
      </v-card-text>
    </v-card>
  </v-flex>
</template>

// angular/src/app/modules/recipe/components/ingredients-data/ingredients-data.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-ingredients-data',
  templateUrl: './ingredients-data.component.html',
  styleUrls: ['./ingredients-data.component.scss']
})
export class IngredientsDataComponent implements OnInit {
  @Input()
  public totalNutrients: any[] = [];

  @Input()
  public totalWeight: number;

  @Input()
  public totalCalories: number;

  constructor() { }

  ngOnInit() {
  }
}

<div fxFlex *ngIf="totalNutrients.length">
  <mat-card >
    <mat-card-header>
      <mat-card-title>
        <h2 class="mat-headline">Total nutrients</h2>
      </mat-card-title>
    </mat-card-header>
    <mat-card-content>
      <h3 class="mat-subheading-1">Calories: {{ totalCalories }}cal</h3>
      <h3 class="mat-subheading-1">Total Weight: {{ totalWeight }}gr</h3>
      <div
        fxLayout="row"
        fxLayoutAlign="space-between end">
        <div
          fxFlex
          class="u-text-center">
          <p class="mat-body-1">Total Nutrients</p>
          <p class="mat-body-1">Total Daily percentage</p>
        </div>

        <div
          fxFlex
          class="u-text-center"
          *ngFor="let nutrient of totalNutrients">
          <div *ngIf="nutrient.totalQuantity.quantity">
            <h3 class="mat-subheading-1">{{ nutrient.label }}</h3>
            <p class="mat-body-1">{{ nutrient.totalQuantity.quantity | number: '0.2-2' }}{{ nutrient.totalQuantity.unit }}</p>
            <p class="mat-body-1">{{ nutrient.totalDaily.quantity | number: '0.2-2' }}{{ nutrient.totalDaily.unit }}</p>
          </div>
        </div>
      </div>
    </mat-card-content>
  </mat-card>
</div>
