// vuejs/src/components/nutrients-macro-chart.vue
<template>
  <v-layout v-bind="rowMdLayout">
    <bar-graph
      v-for="(data, key) in nutritionData"
      :key="key"
      :label="data.totalQuantity.label"
      :percentage="data.totalQuantity.percentage"
    />
  </v-layout>
</template>

<script>
import BarGraph from '@/components/bar-graph';
import layoutMixin from '@/core/layout.mixin';

export default {
  props: {
    nutritionData: {
      type: Array,
      required: true,
    },
  },

  mixins: [layoutMixin],

  components: {
    BarGraph,
  },
};
</script>

// react/src/modules/recipe/components/nutrients-macro-chart/NutrientsMacroChart.js
import React, { Component } from 'react';
import './NutrientsMacroChart.css';
import BarGraph from '../../../../components/bar-graph/BarGraph';

class NutrientsMacroChart extends Component {

  render() {
    const bars = this.props.nutritionData.map((data, index) => {
      const percentage = data.totalQuantity.percentage;
      const label = data.totalQuantity.label;

      console.log(label, percentage);
      return (
        <BarGraph
          key={index}
          label={label}
          percentage={percentage}/>
      )
    });
    return (
      <div className="nutrients-macro-chart">
        {bars}
      </div>
    );
  }
}

export default NutrientsMacroChart;
