// react/src/components/bar-graph/BarGraph.jsx
import React, { Component } from 'react';
import './BarGraph.css';

class BarGraph extends Component {

  get classes () {
    return `bar-graph bar-graph--${this.props.label.toLowerCase()}`;
  }

  get width () {
    return `${this.props.percentage}%`;
  }

  render() {
    if (!this.props.percentage) return false;

    return (
      <div
        style={{width : `${this.width}`}}
        className={this.classes}>
        <p>{this.props.label} {this.width}</p>
      </div>
    );
  }
}

export default BarGraph;

// angular/src/app/components/bar-graph/bar-graph.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-bar-graph',
  templateUrl: './bar-graph.component.html',
  styleUrls: ['./bar-graph.component.scss']
})
export class BarGraphComponent implements OnInit {
  @Input()
  public label = '';

  @Input()
  public percentage = '';

  constructor() { }

  ngOnInit() {
  }

  get width (): string {
    return `${this.percentage}%`;
  }

  get classes (): string {
    return `bar-graph bar-graph--${this.label.toLowerCase()}`;
  }
}

<div
  *ngIf="percentage"
  [className]="classes"
  [style.width]="width">
  <p>{{ label }} {{ width }}</p>
</div>
