// react/src/modules/recipe/components/nutrients-macro-chart/NutrientsMacroChart.jsx
import React, { Component } from 'react';
import './NutrientsMacroChart.css';
import BarGraph from '../../../../components/bar-graph/BarGraph';

class NutrientsMacroChart extends Component {

  render() {
    if (!this.props.nutritionData) return false;
    const bars = this.props.nutritionData.map((data, index) => {
      const percentage = data.totalQuantity.percentage;
      const label = data.totalQuantity.label;

      return (
        <BarGraph
          key={index}
          label={label}
          percentage={percentage}/>
      )
    });
    return (
      <div className="nutrients-macro-chart">
        {bars}
      </div>
    );
  }
}

export default NutrientsMacroChart;

// angular/src/app/modules/recipe/components/nutrients-macro-chart/nutrients-macro-chart.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-nutrients-macro-chart',
  templateUrl: './nutrients-macro-chart.component.html',
  styleUrls: ['./nutrients-macro-chart.component.scss']
})
export class NutrientsMacroChartComponent implements OnInit {
  @Input()
  public nutritionData;

  constructor() { }

  ngOnInit() {
  }
}

<div fxLayout="column">
  <app-bar-graph
    *ngFor="let data of nutritionData"
    [label]="data.totalQuantity.label"
    [percentage]="data.totalQuantity.percentage"></app-bar-graph>
</div>
