// react/src/recipe/components/ingredients-data/IngredientsData.js
import React, { Component } from 'react';
import './IngredientsData.css';

import nutritionService from '../../../core/nutrition.service';
import { MACRO_NUTRIENTS } from '../../../core/edamam.constant';

import NutrientsMacroChart from '../nutrients-macro-chart/NutrientsMacroChart';

class IngredientsData extends Component {

  get totalNutrients () {
    return this.getTotalNutrients();
  }

  get totalCalories () {
    return nutritionService.getTotalCalories(this.props.ingredients);
  }

  get totalWeight () {
    return nutritionService.getTotalWeight(this.props.ingredients);
  }

  getTotalNutrients () {
    return MACRO_NUTRIENTS.map((nutrient) => {
      const totalQuantity = this.totalQuantityFor(nutrient);
      const totalDaily = this.totalDailyIntakeFor(nutrient);

      return {
        label: totalQuantity.label,
        totalQuantity: {
          ...totalQuantity,
        },
        totalDaily: {
          ...totalDaily,
        },
      };
    });
  }

  totalQuantityFor (nutrient) {
    return this.nutritionService.getTotalForNutrient(this.ingredients, 'totalNutrients', nutrient, this.totalCalories);
  }

  totalDailyIntakeFor (nutrient) {
    return this.nutritionService.getTotalForNutrient(this.ingredients, 'totalDaily', nutrient);
  }
  render() {
    if (!this.props.ingredients.length) return (<div></div>);

    const nutrientsDetails = this.totalNutrients.map((nutrient) => 
      <div>
        <h3>{ nutrient.label }</h3>
        <p>{ nutrient.totalQuantity.quantity } { nutrient.totalQuantity.unit }</p>
        <p>{ nutrient.totalDaily.quantity } { nutrient.totalDaily.unit }</p>
      </div>
    );

    return(
      <div>
        <div>
          <h2>Total nutrients</h2>
          <h3>Calories: { this.totalCalories }cal</h3>
          <h3>Total Weight: { this.totalWeight }gr</h3>
          <div>
            <div>
              <p>Total Nutrients</p>
              <p>Total Daily percentage</p>
            </div>
            <div class="u-text-center">
              {nutrientsDetails}
            </div>
          </div>
        </div>
        <div>
          <h2>Macro in recipe</h2>
          <p>Based on 4 calories per gram of carbs and protein, and 9 calories per gram of fat.</p>
          <p>Those numbers are approximation only, as the number of calories per macro change per ingredient and depend on quality and other factor.</p>
          <NutrientsMacroChart nutritionData={this.totalNutrients}></NutrientsMacroChart>
      </div>
    </div>
    );
  }
}

export default IngredientsData;

// angular/src/app/recipe/components/ingredients-data/ingredients-data.component.ts
import { INutrientsValue } from './../../recipe.interface';
import { MACRO_NUTRIENTS } from '@/recipe/edamam.constant';
import { IIngredient } from '@/recipe/recipe.interface';
import { Component, OnInit, Input } from '@angular/core';
import NutritionService from '@/recipe/nutrition.service';

@Component({
  selector: 'app-ingredients-data',
  templateUrl: './ingredients-data.component.html',
  styleUrls: ['./ingredients-data.component.scss']
})
export class IngredientsDataComponent implements OnInit {
  @Input()
  public ingredients: IIngredient[] = [];

  constructor(
    private nutritionService: NutritionService,
  ) { }

  ngOnInit() {
  }

  get totalNutrients () {
    return this.getTotalNutrients();
  }

  get totalCalories (): number {
    return this.nutritionService.getTotalCalories(this.ingredients);
  }

  get totalWeight (): number {
    return this.nutritionService.getTotalWeight(this.ingredients);
  }

  getTotalNutrients () {
    return MACRO_NUTRIENTS.map((nutrient) => {
      const totalQuantity = this.totalQuantityFor(nutrient);
      const totalDaily = this.totalDailyIntakeFor(nutrient);

      return {
        label: totalQuantity.label,
        totalQuantity: {
          ...totalQuantity,
        },
        totalDaily: {
          ...totalDaily,
        },
      };
    });
  }

  totalQuantityFor (nutrient): INutrientsValue {
    return this.nutritionService.getTotalForNutrient(this.ingredients, 'totalNutrients', nutrient, this.totalCalories);
  }

  totalDailyIntakeFor (nutrient): INutrientsValue {
    return this.nutritionService.getTotalForNutrient(this.ingredients, 'totalDaily', nutrient);
  }
}

<div
  *ngIf="ingredients.length"
  fxLayout="column"
  fxLayoutGap="10px">
  <div fxFlex>
    <mat-card >
      <mat-card-header>
        <mat-card-title>
          <h2>Total nutrients</h2>
        </mat-card-title>
      </mat-card-header>
      <mat-card-content>
        <h3>Calories: {{ totalCalories }}cal</h3>
        <h3>Total Weight: {{ totalWeight }}gr</h3>
        <div
          fxLayout="row"
          fxLayoutAlign="space-between end">
          <div
            fxFlex
            class="u-text-center">
            <p>Total Nutrients</p>
            <p>Total Daily percentage</p>
          </div>

          <div
            fxFlex
            class="u-text-center"
            *ngFor="let nutrient of totalNutrients">
            <h3>{{ nutrient.label }}</h3>
            <p>{{ nutrient.totalQuantity.quantity | number }}{{ nutrient.totalQuantity.unit }}</p>
            <p>{{ nutrient.totalDaily.quantity | number }}{{ nutrient.totalDaily.unit }}</p>
          </div>
        </div>
      </mat-card-content>
    </mat-card>
  </div>
  <div fxFlex>
    <mat-card>
      <mat-card-header>
        <mat-card-title>
          <h2>Macro in recipe</h2>
        </mat-card-title>
      </mat-card-header>
      <mat-card-content>
        <p>Based on 4 calories per gram of carbs and protein, and 9 calories per gram of fat.</p>
        <p>Those numbers are approximation only, as the number of calories per macro change per ingredient and depend on quality and other factor.</p>
      </mat-card-content>
      <app-nutrients-macro-chart [nutritionData]="totalNutrients"></app-nutrients-macro-chart>
    </mat-card>
  <div>
</div>
