// react/src/recipe/components/search-ingredient/SearchIngredient.js
import './SearchIngredient.css';

import React, { Component } from 'react';
import { Typography, TextField, Button, Card, CardContent, Grid, CircularProgress } from '@material-ui/core';

class SearchIngredient extends Component {
  constructor(props) {
    super(props);

    this.state = {
      ingredientName: '',
      numberOfServings: 1,
    };
  }

  onIngredientChange = (event) => {
    this.setState({ ingredientName : event.target.value });
  }

  onNumberOfServingsChange = (event) => {
    this.setState({ numberOfServings : event.target.value });
  }

  onSubmit = (event) => {
    event.preventDefault();
    this.props.add(this.state.ingredientName, this.state.numberOfServings);
  }
  
  render() {
    let buttonContent = '';

    if (this.props.isFetching) {
      buttonContent = <CircularProgress style={{ color: '#fff' }} />;
    } else {
      buttonContent = 'Add ingredient';
    }
    return (
      <Card className="u-push-top">
        <CardContent>
          <Typography
            gutterBottom 
            variant="headline"
            component="h2">
            What do you have in your fridge?
          </Typography>          
          <form className="search" onSubmit={this.onSubmit}>
            <Grid 
              container
              spacing={8}
              justify="space-between">
              <Grid
                item
                xs={12} 
                sm={6}>
                <TextField
                  fullWidth
                  label="Find an ingredient"
                  value={this.state.ingredientName} 
                  placeholder="Ex: 200gr chicken"
                  onChange={this.onIngredientChange}/>
              </Grid>
              <Grid item>
                <TextField
                  label="Number of servings"
                  value={this.state.numberOfServings} 
                  onChange={this.onNumberOfServingsChange}/>
              </Grid>
              <Button
                disabled={!this.state.ingredientName}
                type="submit"
                variant="raised"
                color="primary">
                {buttonContent}
              </Button>
            </Grid>
          </form>
        </CardContent>
      </Card>
    );
  }
}

export default SearchIngredient;

// angular/src/app/modules/recipe/components/search-ingredient/search-ingredient.component.ts
import { Component, OnInit, Output, EventEmitter } from '@angular/core';
import { FormBuilder, FormGroup } from '@angular/forms';

@Component({
  selector: 'app-search-ingredient',
  templateUrl: './search-ingredient.component.html',
  styleUrls: ['./search-ingredient.component.scss']
})
export class SearchIngredientComponent implements OnInit {
  public ingredient: string;
  public numberOfServing = 1;

  @Output()
  public add = new EventEmitter<FormGroup>();

  public form = this.fb.group({
    numberOfServing: '1',
    ingredient: '',
  });

  constructor(private fb: FormBuilder) {}

  get isDisabled(): boolean {
    return !this.form.value.ingredient;
  }

  ngOnInit() {
  }

  onSubmit() {
    this.add.emit(this.form.value);
    this.form.setValue({
      numberOfServing: '1',
      ingredient: '',
    });
  }
}

<mat-card class="search-ingredient">
  <mat-card-header>
    <mat-card-title>
      <h2 class="mat-headline">What do you have in your fridge?</h2>
    </mat-card-title>
  </mat-card-header>
  <mat-card-content>
    <form
      [formGroup]="form"
      (submit)="onSubmit()">
      <div
        fxLayout.xs="column"
        fxLayoutAlign="space-between center">
        <mat-form-field fxFlex="50%">
          <input
            matInput
            placeholder="Ingredient and quantity"
            formControlName="ingredient">
          <mat-hint align="start">
            <strong>Example: 200gr chicken</strong>
          </mat-hint>
        </mat-form-field>
        <mat-form-field fxFlex="20%">
          <input
            matInput
            placeholder="Number of servings"
            formControlName="numberOfServing">
        </mat-form-field>
        <button
          mat-button
          disabled="{{ isDisabled }}"
          mat-raised-button
          type="submit"
          color="primary">
          Add
        </button>
      </div>
    </form>

  </mat-card-content>
</mat-card>
