// angular/src/app/modules/recipe/components/nutrition-macro/nutrition-macro.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-nutrition-macro',
  templateUrl: './nutrition-macro.component.html',
  styleUrls: ['./nutrition-macro.component.scss']
})
export class NutritionMacroComponent implements OnInit {
  @Input()
  public totalNutrients: any[] = [];

  constructor() { }

  ngOnInit() {
  }

}

<div fxFlex *ngIf="totalNutrients.length">
  <mat-card>
    <mat-card-header>
      <mat-card-title>
        <h2 class="mat-headline">Macro in recipe</h2>
      </mat-card-title>
    </mat-card-header>
    <mat-card-content>
      <p class="mat-body-1">Based on 4 calories per gram of carbs and protein, and 9 calories per gram of fat.</p>
      <p class="mat-body-1">Those numbers are approximation only, as the number of calories per macro change per ingredient and depend on quality and other factor.</p>
    </mat-card-content>
    <app-nutrients-macro-chart [nutritionData]="totalNutrients"></app-nutrients-macro-chart>
  </mat-card>
</div>

// vuejs/src/components/nutrition-macro.vue
<template>
  <v-flex
    xs12
    v-if="totalNutrients.length"
  >
    <v-card>
      <v-card-title>
        <h2 class="headline">
          Macro in recipe
        </h2>
      </v-card-title>
      <v-card-text>
        <p class="body-1">
          Based on 4 calories per gram of carbs and protein, and 9 calories per gram of fat.
        </p>
        <p class="body-1">
          Those numbers are approximation only, as the number of calories per macro change per ingredient and depend on quality and other factor.
        </p>
        <nutrients-macro-chart :nutrition-data="totalNutrients" />
      </v-card-text>
    </v-card>
  </v-flex>
</template>

<script>
import NutrientsMacroChart from '@/components/nutrients-macro-chart';

export default {
  components: {
    NutrientsMacroChart,
  },

  props: {
    totalNutrients: {
      type: Array,
      required: true,
    },
  },
};
</script>
